# History Tracers configuration file

#
# Directory containing files used for developing new content
#
srcpath = "/usr/share/historytracers/"

#
# Directory where content will be delivered to users
#
contentpath = "/usr/share/historytracers/www/"

#
# Directory where the software will store log files
#
logpath = "/var/log/historytracers/"
