#!/bin/sh
set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Reload systemd and reset failed state
        systemctl daemon-reload >/dev/null 2>&1 || true
        systemctl reset-failed historytracers.service >/dev/null 2>&1 || true
    ;;
esac

exit 0
