#!/bin/sh
set -e

case "$1" in
    remove|upgrade)
        # Stop service before removal or upgrade
        systemctl stop historytracers.service >/dev/null 2>&1 || true
        systemctl disable historytracers.service >/dev/null 2>&1 || true
    ;;
esac

exit 0
