# History Tracers configuration file

#
# Directory containing files used for developing new content
#
srcpath = "./"

#
# Directory where content will be delivered to users
#
contentpath = "./www/"

#
# Directory where the software will store log files
#
logpath = "/var/log/historytracers/"
